name: 'ravenstack'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    -   "target"
    -   "dbt_packages"

quoting:
    database: true

models:
    ravenstack:
        staging:
            +materialized: view
        marts:
            +materialized: table
